"""baseline

Revision ID: 542248509395
Revises: 
Create Date: 2026-04-20 08:56:52.947229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('remote_addr', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_actor_created', ['actor', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_audit_log_route_created', ['route', 'created_at'], unique=False)

    op.create_table('engagements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('ruleset', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_mode'), ['mode'], unique=False)

    op.create_table('intel_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cursor', sa.JSON(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intel_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intel_sources_name'), ['name'], unique=True)

    op.create_table('learning_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_event_id', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_doc', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_items_source_event_id'), ['source_event_id'], unique=False)

    op.create_table('provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=False),
    sa.Column('default_model', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_configs_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_provider_configs_provider_type'), ['provider_type'], unique=False)

    op.create_table('worker_runtime_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_run_id', sa.String(length=36), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_runtime_status', schema=None) as batch_op:
        batch_op.create_index('ix_worker_runtime_status_heartbeat', ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_runtime_status_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index('ix_worker_runtime_status_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_runtime_status_worker_id'), ['worker_id'], unique=True)

    op.create_table('vulnerability_intel',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('cve_ids', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=False),
    sa.Column('epss', sa.Float(), nullable=False),
    sa.Column('epss_percentile', sa.Float(), nullable=False),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('scanner_template_available', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['intel_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_vulnerability_intel_source_external')
    )
    with op.batch_alter_table('vulnerability_intel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_exploit_available'), ['exploit_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_kev'), ['kev'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_scanner_template_available'), ['scanner_template_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_source_id'), ['source_id'], unique=False)

    op.create_table('workspace_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('repo_path', sa.String(length=512), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('resumed_from_run_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_runs_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_runs_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_runs_workspace_id'), ['workspace_id'], unique=True)

    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_path', sa.String(length=1024), nullable=False),
    sa.Column('prompt_path', sa.String(length=1024), nullable=False),
    sa.Column('log_path', sa.String(length=1024), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_sessions_run_id'), ['run_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('response_note', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_facts_run_created', ['run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_facts_run_kind_created', ['run_id', 'kind', 'created_at'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('reproduction', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_run_id'), ['run_id'], unique=False)

    op.create_table('operator_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('applies_to', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_notes_run_id'), ['run_id'], unique=False)

    op.create_table('run_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_messages_role'), ['role'], unique=False)
        batch_op.create_index('ix_run_messages_run_created', ['run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_messages_run_id'), ['run_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_run_id'), ['run_id'], unique=False)

    op.create_table('vulnerability_intel_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intel_id', sa.String(length=36), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=False),
    sa.Column('reference_value', sa.String(length=1024), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intel_id'], ['vulnerability_intel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intel_id', 'reference_type', 'reference_value', name='uq_vuln_intel_reference')
    )
    with op.batch_alter_table('vulnerability_intel_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_references_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_references_intel_id'), ['intel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_references_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_intel_references_reference_value'), ['reference_value'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=255), nullable=False),
    sa.Column('error_class', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_workflow_executions_run_status', ['run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_status'), ['status'], unique=False)
        batch_op.create_index('ix_workflow_executions_status_updated', ['status', 'updated_at'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_task_id'), ['task_id'], unique=False)

    op.create_table('run_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('phase_name', sa.String(length=64), nullable=False),
    sa.Column('phase_attempt', sa.Integer(), nullable=False),
    sa.Column('checkpoint_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_checkpoints_is_latest'), ['is_latest'], unique=False)
        batch_op.create_index('ix_run_checkpoints_lookup', ['workflow_id', 'phase_name', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_checkpoints_phase_name'), ['phase_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_checkpoints_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_run_checkpoints_run_phase_latest', ['run_id', 'phase_name', 'is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_checkpoints_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_session_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_agent_session_id'), ['agent_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_run_events_run_created', ['run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_run_events_run_sequence', ['run_id', 'sequence'], unique=False)
        batch_op.create_index('ix_run_events_run_type_seq', ['run_id', 'event_type', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_sequence'), ['sequence'], unique=False)

    op.create_table('run_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('phase_name', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_run_metrics_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_metrics_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_metrics_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_run_metrics_run_metric', ['run_id', 'metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_metrics_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_run_metrics_workflow_phase', ['workflow_id', 'phase_name'], unique=False)

    op.create_table('workflow_phase_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('phase_name', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_class', sa.String(length=32), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'phase_name', 'attempt', name='uq_workflow_phase_attempt')
    )
    with op.batch_alter_table('workflow_phase_runs', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_phase_runs_claim', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index('ix_workflow_phase_runs_latest', ['workflow_id', 'phase_name', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_phase_runs_phase_name'), ['phase_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_phase_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_workflow_phase_runs_run_phase', ['run_id', 'phase_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_phase_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_phase_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('memory_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_events_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_events_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_events_run_id'), ['run_id'], unique=False)

    op.create_table('worker_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('phase_name', sa.String(length=64), nullable=False),
    sa.Column('phase_run_id', sa.String(length=36), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phase_run_id'], ['workflow_phase_runs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workspace_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_leases_phase_name'), ['phase_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_leases_phase_run_id'), ['phase_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_leases_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_worker_leases_run_phase', ['run_id', 'phase_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_leases_status'), ['status'], unique=False)
        batch_op.create_index('ix_worker_leases_status_expiry', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index('ix_worker_leases_worker_heartbeat', ['worker_id', 'heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_leases_worker_id'), ['worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_leases_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_leases_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_worker_leases_worker_id'))
        batch_op.drop_index('ix_worker_leases_worker_heartbeat')
        batch_op.drop_index('ix_worker_leases_status_expiry')
        batch_op.drop_index(batch_op.f('ix_worker_leases_status'))
        batch_op.drop_index('ix_worker_leases_run_phase')
        batch_op.drop_index(batch_op.f('ix_worker_leases_run_id'))
        batch_op.drop_index(batch_op.f('ix_worker_leases_phase_run_id'))
        batch_op.drop_index(batch_op.f('ix_worker_leases_phase_name'))

    op.drop_table('worker_leases')
    with op.batch_alter_table('memory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_memory_events_classification'))
        batch_op.drop_index(batch_op.f('ix_memory_events_action_id'))

    op.drop_table('memory_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_action_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('workflow_phase_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_phase_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_phase_runs_status'))
        batch_op.drop_index('ix_workflow_phase_runs_run_phase')
        batch_op.drop_index(batch_op.f('ix_workflow_phase_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_phase_runs_phase_name'))
        batch_op.drop_index('ix_workflow_phase_runs_latest')
        batch_op.drop_index('ix_workflow_phase_runs_claim')

    op.drop_table('workflow_phase_runs')
    with op.batch_alter_table('run_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_run_metrics_workflow_phase')
        batch_op.drop_index(batch_op.f('ix_run_metrics_workflow_id'))
        batch_op.drop_index('ix_run_metrics_run_metric')
        batch_op.drop_index(batch_op.f('ix_run_metrics_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_metrics_metric_name'))
        batch_op.drop_index('ix_run_metrics_created')

    op.drop_table('run_metrics')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_sequence'))
        batch_op.drop_index('ix_run_events_run_type_seq')
        batch_op.drop_index('ix_run_events_run_sequence')
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))
        batch_op.drop_index('ix_run_events_run_created')
        batch_op.drop_index(batch_op.f('ix_run_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_run_events_agent_session_id'))

    op.drop_table('run_events')
    with op.batch_alter_table('run_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_checkpoints_workflow_id'))
        batch_op.drop_index('ix_run_checkpoints_run_phase_latest')
        batch_op.drop_index(batch_op.f('ix_run_checkpoints_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_checkpoints_phase_name'))
        batch_op.drop_index('ix_run_checkpoints_lookup')
        batch_op.drop_index(batch_op.f('ix_run_checkpoints_is_latest'))

    op.drop_table('run_checkpoints')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_task_id'))

    op.drop_table('actions')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_executions_status_updated')
        batch_op.drop_index(batch_op.f('ix_workflow_executions_status'))
        batch_op.drop_index('ix_workflow_executions_run_status')
        batch_op.drop_index(batch_op.f('ix_workflow_executions_run_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('vulnerability_intel_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_references_reference_value'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_references_reference_type'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_references_intel_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_references_cve_id'))

    op.drop_table('vulnerability_intel_references')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_run_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('run_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_messages_run_id'))
        batch_op.drop_index('ix_run_messages_run_created')
        batch_op.drop_index(batch_op.f('ix_run_messages_role'))

    op.drop_table('run_messages')
    with op.batch_alter_table('operator_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_notes_run_id'))

    op.drop_table('operator_notes')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_run_id'))

    op.drop_table('findings')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index('ix_facts_run_kind_created')
        batch_op.drop_index(batch_op.f('ix_facts_run_id'))
        batch_op.drop_index('ix_facts_run_created')
        batch_op.drop_index(batch_op.f('ix_facts_kind'))

    op.drop_table('facts')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_run_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_sessions_role'))

    op.drop_table('agent_sessions')
    with op.batch_alter_table('workspace_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_runs_mode'))
        batch_op.drop_index(batch_op.f('ix_workspace_runs_engagement_id'))

    op.drop_table('workspace_runs')
    with op.batch_alter_table('vulnerability_intel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_source_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_scanner_template_available'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_priority_score'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_kev'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_external_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_intel_exploit_available'))

    op.drop_table('vulnerability_intel')
    with op.batch_alter_table('worker_runtime_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_runtime_status_worker_id'))
        batch_op.drop_index('ix_worker_runtime_status_status')
        batch_op.drop_index(batch_op.f('ix_worker_runtime_status_heartbeat_at'))
        batch_op.drop_index('ix_worker_runtime_status_heartbeat')

    op.drop_table('worker_runtime_status')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_provider_type'))
        batch_op.drop_index(batch_op.f('ix_provider_configs_name'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('learning_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_items_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_learning_items_category'))

    op.drop_table('learning_items')
    with op.batch_alter_table('intel_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intel_sources_name'))

    op.drop_table('intel_sources')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_mode'))

    op.drop_table('engagements')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_route_created')
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index('ix_audit_log_actor_created')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
