import { FormEvent } from "react";
import { ProviderConfig, Run } from "../../api";

export function ProviderSettings(props: { apiToken: string; setApiToken: (token: string) => void; providers: ProviderConfig[]; selectedRun: Run | null; routedProviderId: string; setRoutedProviderId: (value: string) => void; onRoute: () => void; providerForm: { name: string; provider_type: string; default_model: string; base_url: string; secret: string }; setProviderForm: (value: { name: string; provider_type: string; default_model: string; base_url: string; secret: string }) => void; onSave: (event: FormEvent) => void }) {
  return <article className="panel settings-panel"><header><h3>Runtime Settings</h3><span>Codex first, APIs optional</span></header><label>UI API token<input value={props.apiToken} onChange={(event) => props.setApiToken(event.target.value)} placeholder="Bearer token for protected APIs" /></label>{props.selectedRun ? <div className="provider-route"><label>Run provider route<select value={props.routedProviderId} onChange={(event) => props.setRoutedProviderId(event.target.value)}><option value="">codex</option>{props.providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name} / {provider.provider_type}</option>)}</select></label><button type="button" onClick={props.onRoute}>Apply Route</button></div> : null}<form className="provider-form" onSubmit={props.onSave}><label>Name<input value={props.providerForm.name} onChange={(event) => props.setProviderForm({ ...props.providerForm, name: event.target.value })} /></label><label>Type<select value={props.providerForm.provider_type} onChange={(event) => props.setProviderForm({ ...props.providerForm, provider_type: event.target.value })}>{["openai", "anthropic", "gemini", "ollama", "bedrock", "deepseek", "glm", "kimi", "qwen", "openrouter", "custom"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Model<input value={props.providerForm.default_model} onChange={(event) => props.setProviderForm({ ...props.providerForm, default_model: event.target.value })} /></label><label>Base URL<input value={props.providerForm.base_url} onChange={(event) => props.setProviderForm({ ...props.providerForm, base_url: event.target.value })} /></label><label>Secret<input type="password" value={props.providerForm.secret} onChange={(event) => props.setProviderForm({ ...props.providerForm, secret: event.target.value })} placeholder="requires VANTIX_SECRET_KEY" /></label><button type="submit">Save Provider</button></form><List items={props.providers.map((provider) => `${provider.name}: ${provider.provider_type} / ${provider.enabled ? "enabled" : "disabled"} / key=${provider.has_key ? "yes" : "no"}`)} empty="No optional providers configured." /></article>;
}

function List({ items, empty }: { items: string[]; empty: string }) {
  if (!items.length) return <p className="empty">{empty}</p>;
  return <ul>{items.map((item, index) => <li key={`${item}-${index}`}><span>{item}</span></li>)}</ul>;
}
